version: '3'

services:
  personal-site:
    image: lrh-profile:latest
    build: .
    container_name: lrh-profile-image
    ports:
      - "80:80"
    restart: always
    networks:
      - web-network
    user: nginx

networks:
  web-network:
    driver: bridge
