version: '3'

services:
  personal-site:
    image: lrh-profile:latest
    build: .
    container_name: lrh-profile-image
    ports:
      - "80:80"
    volumes:
      - ./lrh_profile_html:/usr/share/nginx/html
    restart: always
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
