version: '3'

services:
  personal-site:
    build: .
    container_name: lllrrrhhh/lrh-profile-image
    ports:
      - "8080:80"
    volumes:
      - ./lrh_profile_html:/usr/share/nginx/html
    restart: always
